language: node_js
node_js:
- '12.0.0'
script:
- yarn run lint
- yarn run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/z-games-six-nimmt
    branch: master
  skip_cleanup: true
  api_key:
    secure: B+FnakGqz9KVdXu/Sla+qn4nfRnZA4+ebAOvlVrJSG1wzn3icPGFJ6hh3gO8UA4Q6+nAuaPSAd6v3rwGWbkeD64CKaQyXjBBj709vGOHGY/A29dddi7RlUGgPsNifCVxRsLml/w3L11t8/mpWWkt+MMof07JfYQrqotmm0oBlksQDDCGeVm8e05E1xmhjt6kq9zqp1cKkithcee/khWWEavFJ3qKz7MUrkjX/TIlkjkvghwJ2DfBpzLqfEGt0CZ5ND8GgXQ3HkDE1VgfIsllIsgZt9jZyvnAQ8HhkTUv7Vkx8stLuE8p58ESbSzmCYJFESAjsUnDyEKSKMCdIczBTGq5qxaAuj0LqSehxT2M343fMpcnTyr/lnroc28Haw7igkYiX5mxTt2PTtfvrOpoTlbqeIzjeMo/FcjDKRnCaCkVwzy16S6Cm1HuZnxRSV5EKLs3+bafBfPWjTkvxiLiHO7r1mLp9YED2/9MiD14qNkkv6SnZ/om0cjpkmQiJK4GzYHDWskyWvHbSOz5YqVm5ssK7fhwdtzRt/uzNN0sQshI3QoalOZHSuVk/p6MSaxJwRwSjLufShLJjPxYIq/A92MvtDB1IFLTnmL7OCgmP4+3CtUTJcVS0eNzXC6g6J/2vxbQO55G9BQ/0t3lrEjJx2372LdrdvbTx0D6Ug4lhcI=
